/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['config.js']) {
  _$jscoverage['config.js'] = [];
}
_$jscoverage['config.js'].source = [];
