/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['main.js']) {
  _$jscoverage['main.js'] = [];
  _$jscoverage['main.js'][1] = 0;
  _$jscoverage['main.js'][3] = 0;
  _$jscoverage['main.js'][4] = 0;
  _$jscoverage['main.js'][7] = 0;
}
_$jscoverage['main.js'][1]++;
var express = require("express"), app = express();
_$jscoverage['main.js'][3]++;
app.get("/", (function (req, res) {
  _$jscoverage['main.js'][4]++;
  res.send("Hello, Express!");
}));
_$jscoverage['main.js'][7]++;
module.exports = app;
_$jscoverage['main.js'].source = ["var express = require('express'), app = express();","","app.get('/', function (req, res) {","    res.send('Hello, Express!')","})","","module.exports = app;"];
